name = "zme"
main = "./workers/bootstrap.ts"
compatibility_date = "2026-06-03"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
ZPAN_BASE_URL = "http://localhost:5174"

[observability]
enabled = true
