// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiAdminDownloadersByIdData, DeleteApiAdminDownloadersByIdErrors, DeleteApiAdminDownloadersByIdResponses, GetApiAdminDownloadersData, GetApiAdminDownloadersErrors, GetApiAdminDownloadersResponses, GetApiDownloadTasksByIdData, GetApiDownloadTasksByIdErrors, GetApiDownloadTasksByIdResponses, GetApiDownloadTasksData, GetApiDownloadTasksErrors, GetApiDownloadTasksEventsData, GetApiDownloadTasksEventsErrors, GetApiDownloadTasksEventsResponse, GetApiDownloadTasksEventsResponses, GetApiDownloadTasksResponses, PatchApiAdminDownloadersByIdData, PatchApiAdminDownloadersByIdErrors, PatchApiAdminDownloadersByIdResponses, PatchApiDownloadTasksByIdData, PatchApiDownloadTasksByIdErrors, PatchApiDownloadTasksByIdResponses, PatchApiObjectsByIdData, PatchApiObjectsByIdErrors, PatchApiObjectsByIdResponses, PostApiAdminDownloadersData, PostApiAdminDownloadersErrors, PostApiAdminDownloadersResponses, PostApiAuthDeviceCodeData, PostApiAuthDeviceCodeResponses, PostApiAuthDeviceTokenData, PostApiAuthDeviceTokenErrors, PostApiAuthDeviceTokenResponses, PostApiDownloaderHeartbeatData, PostApiDownloaderHeartbeatErrors, PostApiDownloaderHeartbeatResponses, PostApiDownloadTasksByIdActionsData, PostApiDownloadTasksByIdActionsErrors, PostApiDownloadTasksByIdActionsResponses, PostApiDownloadTasksData, PostApiDownloadTasksErrors, PostApiDownloadTasksResponses, PostApiObjectsData, PostApiObjectsErrors, PostApiObjectsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiAuthDeviceCode = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthDeviceCodeData, ThrowOnError>): RequestResult<PostApiAuthDeviceCodeResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiAuthDeviceCodeResponses, unknown, ThrowOnError>({
    url: '/api/auth/device/code',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAuthDeviceToken = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthDeviceTokenData, ThrowOnError>): RequestResult<PostApiAuthDeviceTokenResponses, PostApiAuthDeviceTokenErrors, ThrowOnError> => (options.client ?? client).post<PostApiAuthDeviceTokenResponses, PostApiAuthDeviceTokenErrors, ThrowOnError>({
    url: '/api/auth/device/token',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiDownloadTasks = <ThrowOnError extends boolean = false>(options?: Options<GetApiDownloadTasksData, ThrowOnError>): RequestResult<GetApiDownloadTasksResponses, GetApiDownloadTasksErrors, ThrowOnError> => (options?.client ?? client).get<GetApiDownloadTasksResponses, GetApiDownloadTasksErrors, ThrowOnError>({ url: '/api/download-tasks', ...options });

export const postApiDownloadTasks = <ThrowOnError extends boolean = false>(options: Options<PostApiDownloadTasksData, ThrowOnError>): RequestResult<PostApiDownloadTasksResponses, PostApiDownloadTasksErrors, ThrowOnError> => (options.client ?? client).post<PostApiDownloadTasksResponses, PostApiDownloadTasksErrors, ThrowOnError>({
    url: '/api/download-tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiDownloadTasksEvents = <ThrowOnError extends boolean = false>(options?: Options<GetApiDownloadTasksEventsData, ThrowOnError, GetApiDownloadTasksEventsResponse>): Promise<ServerSentEventsResult<GetApiDownloadTasksEventsResponses, GetApiDownloadTasksEventsErrors | void, ThrowOnError>> => (options?.client ?? client).sse.get<GetApiDownloadTasksEventsResponses, GetApiDownloadTasksEventsErrors, ThrowOnError>({ url: '/api/download-tasks/events', ...options });

export const getApiDownloadTasksById = <ThrowOnError extends boolean = false>(options: Options<GetApiDownloadTasksByIdData, ThrowOnError>): RequestResult<GetApiDownloadTasksByIdResponses, GetApiDownloadTasksByIdErrors, ThrowOnError> => (options.client ?? client).get<GetApiDownloadTasksByIdResponses, GetApiDownloadTasksByIdErrors, ThrowOnError>({ url: '/api/download-tasks/{id}', ...options });

export const patchApiDownloadTasksById = <ThrowOnError extends boolean = false>(options: Options<PatchApiDownloadTasksByIdData, ThrowOnError>): RequestResult<PatchApiDownloadTasksByIdResponses, PatchApiDownloadTasksByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchApiDownloadTasksByIdResponses, PatchApiDownloadTasksByIdErrors, ThrowOnError>({
    url: '/api/download-tasks/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiDownloadTasksByIdActions = <ThrowOnError extends boolean = false>(options: Options<PostApiDownloadTasksByIdActionsData, ThrowOnError>): RequestResult<PostApiDownloadTasksByIdActionsResponses, PostApiDownloadTasksByIdActionsErrors, ThrowOnError> => (options.client ?? client).post<PostApiDownloadTasksByIdActionsResponses, PostApiDownloadTasksByIdActionsErrors, ThrowOnError>({
    url: '/api/download-tasks/{id}/actions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiDownloaderHeartbeat = <ThrowOnError extends boolean = false>(options: Options<PostApiDownloaderHeartbeatData, ThrowOnError>): RequestResult<PostApiDownloaderHeartbeatResponses, PostApiDownloaderHeartbeatErrors, ThrowOnError> => (options.client ?? client).post<PostApiDownloaderHeartbeatResponses, PostApiDownloaderHeartbeatErrors, ThrowOnError>({
    url: '/api/downloader/heartbeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiAdminDownloaders = <ThrowOnError extends boolean = false>(options?: Options<GetApiAdminDownloadersData, ThrowOnError>): RequestResult<GetApiAdminDownloadersResponses, GetApiAdminDownloadersErrors, ThrowOnError> => (options?.client ?? client).get<GetApiAdminDownloadersResponses, GetApiAdminDownloadersErrors, ThrowOnError>({ url: '/api/admin/downloaders', ...options });

export const postApiAdminDownloaders = <ThrowOnError extends boolean = false>(options: Options<PostApiAdminDownloadersData, ThrowOnError>): RequestResult<PostApiAdminDownloadersResponses, PostApiAdminDownloadersErrors, ThrowOnError> => (options.client ?? client).post<PostApiAdminDownloadersResponses, PostApiAdminDownloadersErrors, ThrowOnError>({
    url: '/api/admin/downloaders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiAdminDownloadersById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiAdminDownloadersByIdData, ThrowOnError>): RequestResult<DeleteApiAdminDownloadersByIdResponses, DeleteApiAdminDownloadersByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteApiAdminDownloadersByIdResponses, DeleteApiAdminDownloadersByIdErrors, ThrowOnError>({ url: '/api/admin/downloaders/{id}', ...options });

export const patchApiAdminDownloadersById = <ThrowOnError extends boolean = false>(options: Options<PatchApiAdminDownloadersByIdData, ThrowOnError>): RequestResult<PatchApiAdminDownloadersByIdResponses, PatchApiAdminDownloadersByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchApiAdminDownloadersByIdResponses, PatchApiAdminDownloadersByIdErrors, ThrowOnError>({
    url: '/api/admin/downloaders/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiObjects = <ThrowOnError extends boolean = false>(options: Options<PostApiObjectsData, ThrowOnError>): RequestResult<PostApiObjectsResponses, PostApiObjectsErrors, ThrowOnError> => (options.client ?? client).post<PostApiObjectsResponses, PostApiObjectsErrors, ThrowOnError>({
    url: '/api/objects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const patchApiObjectsById = <ThrowOnError extends boolean = false>(options: Options<PatchApiObjectsByIdData, ThrowOnError>): RequestResult<PatchApiObjectsByIdResponses, PatchApiObjectsByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchApiObjectsByIdResponses, PatchApiObjectsByIdErrors, ThrowOnError>({
    url: '/api/objects/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
