// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiDownloadsTasksByIdData, DeleteApiDownloadsTasksByIdErrors, DeleteApiDownloadsTasksByIdResponses, GetApiDownloadsTasksByIdData, GetApiDownloadsTasksByIdErrors, GetApiDownloadsTasksByIdResponses, GetApiDownloadsTasksData, GetApiDownloadsTasksErrors, GetApiDownloadsTasksResponses, GetApiEventsData, GetApiEventsErrors, GetApiEventsResponse, GetApiEventsResponses, PatchApiDownloadsTasksByIdData, PatchApiDownloadsTasksByIdErrors, PatchApiDownloadsTasksByIdResponses, PostApiDownloadsTasksByIdAttemptsData, PostApiDownloadsTasksByIdAttemptsErrors, PostApiDownloadsTasksByIdAttemptsResponses, PostApiDownloadsTasksData, PostApiDownloadsTasksErrors, PostApiDownloadsTasksResponses, PutApiDownloadsTasksByIdStatusData, PutApiDownloadsTasksByIdStatusErrors, PutApiDownloadsTasksByIdStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiDownloadsTasks = <ThrowOnError extends boolean = false>(options?: Options<GetApiDownloadsTasksData, ThrowOnError>): RequestResult<GetApiDownloadsTasksResponses, GetApiDownloadsTasksErrors, ThrowOnError> => (options?.client ?? client).get<GetApiDownloadsTasksResponses, GetApiDownloadsTasksErrors, ThrowOnError>({ url: '/api/downloads/tasks', ...options });

export const postApiDownloadsTasks = <ThrowOnError extends boolean = false>(options: Options<PostApiDownloadsTasksData, ThrowOnError>): RequestResult<PostApiDownloadsTasksResponses, PostApiDownloadsTasksErrors, ThrowOnError> => (options.client ?? client).post<PostApiDownloadsTasksResponses, PostApiDownloadsTasksErrors, ThrowOnError>({
    url: '/api/downloads/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiDownloadsTasksById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiDownloadsTasksByIdData, ThrowOnError>): RequestResult<DeleteApiDownloadsTasksByIdResponses, DeleteApiDownloadsTasksByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteApiDownloadsTasksByIdResponses, DeleteApiDownloadsTasksByIdErrors, ThrowOnError>({ url: '/api/downloads/tasks/{id}', ...options });

export const getApiDownloadsTasksById = <ThrowOnError extends boolean = false>(options: Options<GetApiDownloadsTasksByIdData, ThrowOnError>): RequestResult<GetApiDownloadsTasksByIdResponses, GetApiDownloadsTasksByIdErrors, ThrowOnError> => (options.client ?? client).get<GetApiDownloadsTasksByIdResponses, GetApiDownloadsTasksByIdErrors, ThrowOnError>({ url: '/api/downloads/tasks/{id}', ...options });

export const patchApiDownloadsTasksById = <ThrowOnError extends boolean = false>(options: Options<PatchApiDownloadsTasksByIdData, ThrowOnError>): RequestResult<PatchApiDownloadsTasksByIdResponses, PatchApiDownloadsTasksByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchApiDownloadsTasksByIdResponses, PatchApiDownloadsTasksByIdErrors, ThrowOnError>({
    url: '/api/downloads/tasks/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const putApiDownloadsTasksByIdStatus = <ThrowOnError extends boolean = false>(options: Options<PutApiDownloadsTasksByIdStatusData, ThrowOnError>): RequestResult<PutApiDownloadsTasksByIdStatusResponses, PutApiDownloadsTasksByIdStatusErrors, ThrowOnError> => (options.client ?? client).put<PutApiDownloadsTasksByIdStatusResponses, PutApiDownloadsTasksByIdStatusErrors, ThrowOnError>({
    url: '/api/downloads/tasks/{id}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiDownloadsTasksByIdAttempts = <ThrowOnError extends boolean = false>(options: Options<PostApiDownloadsTasksByIdAttemptsData, ThrowOnError>): RequestResult<PostApiDownloadsTasksByIdAttemptsResponses, PostApiDownloadsTasksByIdAttemptsErrors, ThrowOnError> => (options.client ?? client).post<PostApiDownloadsTasksByIdAttemptsResponses, PostApiDownloadsTasksByIdAttemptsErrors, ThrowOnError>({
    url: '/api/downloads/tasks/{id}/attempts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Server-sent events stream
 *
 * A single SSE connection multiplexing several domains via named events:
 *
 * - `jobs` → `{ activeCount }` — background-job set changed (always on)
 * - `notifications` → `{ unreadCount }` — unread count changed (always on)
 * - `download-tasks` → `{ items, total, page, pageSize }` — download tasks changed (opt-in via `?downloadTasks=1`)
 * - `heartbeat` → `{ at }` — keep-alive emitted when nothing changed for a while
 * - `error` → `{ message }` — a domain query failed this tick
 */
export const getApiEvents = <ThrowOnError extends boolean = false>(options?: Options<GetApiEventsData, ThrowOnError, GetApiEventsResponse>): Promise<ServerSentEventsResult<GetApiEventsResponses, GetApiEventsErrors | void, ThrowOnError>> => (options?.client ?? client).sse.get<GetApiEventsResponses, GetApiEventsErrors, ThrowOnError>({ url: '/api/events', ...options });
