// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | (string & {});
};

export type DeviceCode = {
    device_code: string;
    user_code: string;
    verification_uri: string;
    verification_uri_complete: string;
    expires_in: number;
    interval: number;
};

export type DeviceCodeRequest = {
    client_id: string;
    scope: string;
};

export type DeviceToken = {
    access_token: string;
    token_type: string;
    expires_in: number;
    scope: string;
};

export type ErrorResponse = {
    error: string;
};

export type DeviceTokenRequest = {
    grant_type: string;
    device_code: string;
    client_id: string;
};

export type PostApiAuthDeviceCodeData = {
    body: DeviceCodeRequest;
    path?: never;
    query?: never;
    url: '/api/auth/device/code';
};

export type PostApiAuthDeviceCodeResponses = {
    /**
     * Device authorization code
     */
    200: DeviceCode;
};

export type PostApiAuthDeviceCodeResponse = PostApiAuthDeviceCodeResponses[keyof PostApiAuthDeviceCodeResponses];

export type PostApiAuthDeviceTokenData = {
    body: DeviceTokenRequest;
    path?: never;
    query?: never;
    url: '/api/auth/device/token';
};

export type PostApiAuthDeviceTokenErrors = {
    /**
     * Device login error
     */
    400: ErrorResponse;
};

export type PostApiAuthDeviceTokenError = PostApiAuthDeviceTokenErrors[keyof PostApiAuthDeviceTokenErrors];

export type PostApiAuthDeviceTokenResponses = {
    /**
     * Device access token
     */
    200: DeviceToken;
};

export type PostApiAuthDeviceTokenResponse = PostApiAuthDeviceTokenResponses[keyof PostApiAuthDeviceTokenResponses];

export type GetApiDownloadTasksData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        assignedTo?: 'me';
        category?: string;
        tag?: string;
        sortBy?: 'createdAt' | 'source' | 'category' | 'tags' | 'status' | 'progress' | 'eta';
        sortDir?: 'asc' | 'desc';
        page?: number;
        pageSize?: number;
    };
    url: '/api/download-tasks';
};

export type GetApiDownloadTasksErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiDownloadTasksError = GetApiDownloadTasksErrors[keyof GetApiDownloadTasksErrors];

export type GetApiDownloadTasksResponses = {
    /**
     * Download tasks
     */
    200: {
        items: Array<{
            id: string;
            orgId?: string;
            createdBy?: string;
            spec: {
                source: {
                    type: 'http' | 'magnet' | 'torrent_url';
                    uri: string;
                };
                destination: {
                    folder: string;
                    name: string | null;
                };
                labels: {
                    category: string | null;
                    tags: Array<string>;
                };
            };
            status: {
                state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
                attempt: number;
                assignment: {
                    downloaderId: string;
                    assignedAt?: string | null;
                    uploadToken?: string;
                } | null;
                progress: {
                    download: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                };
                billing: {
                    state: 'none' | 'ok' | 'insufficient_credits';
                    authorizedBytes: number;
                    chargedBytes: number;
                    chargedCredits: number;
                };
                output: {
                    objectId: string;
                } | null;
                runtime: {
                    engine?: 'builtin' | 'aria2' | 'qbittorrent';
                    state?: string;
                    phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                    message?: string;
                    updatedAt?: string;
                    progress?: {
                        download: {
                            bytes: number;
                            totalBytes?: number | null;
                            bytesPerSecond: number;
                        };
                        upload: {
                            bytes: number;
                            totalBytes?: number | null;
                            bytesPerSecond: number;
                        };
                    };
                    torrent?: {
                        infoHash?: string;
                        name?: string;
                        seeders?: number;
                        leechers?: number;
                        peers?: number;
                    };
                    seeding?: {
                        enabled?: boolean;
                        active?: boolean;
                        uploadedBytes?: number;
                        uploadBytesPerSecond?: number;
                        ratio?: number;
                        startedAt?: string | null;
                        expiresAt?: string | null;
                    };
                    connections?: number;
                    etaSeconds?: number | null;
                    trackers?: Array<{
                        url: string;
                        status?: string;
                        peers?: number;
                        seeds?: number;
                        leechers?: number;
                        message?: string;
                    }>;
                    peers?: Array<{
                        address: string;
                        client?: string;
                        progress?: number;
                        downloadBps?: number;
                        uploadBps?: number;
                        countryCode?: string;
                        regionCode?: string;
                    }>;
                    files?: Array<{
                        path: string;
                        size: number;
                        completedBytes?: number;
                        selected?: boolean;
                    }>;
                } | null;
                error: {
                    code?: string | null;
                    message: string | null;
                } | null;
                startedAt: string | null;
                finishedAt: string | null;
                updatedAt: string;
            };
            createdAt: string;
        }>;
        total: number;
        page: number;
        pageSize: number;
    };
};

export type GetApiDownloadTasksResponse = GetApiDownloadTasksResponses[keyof GetApiDownloadTasksResponses];

export type PostApiDownloadTasksData = {
    body: {
        source: {
            type: 'http' | 'magnet' | 'torrent_url';
            uri: string;
        };
        targetFolder: string;
        name?: string;
        category?: string;
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/download-tasks';
};

export type PostApiDownloadTasksErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Insufficient credits
     */
    402: {
        error: string;
    };
    /**
     * Download task conflict
     */
    409: {
        error: string;
    };
};

export type PostApiDownloadTasksError = PostApiDownloadTasksErrors[keyof PostApiDownloadTasksErrors];

export type PostApiDownloadTasksResponses = {
    /**
     * Created download task
     */
    201: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string | null;
            };
            labels: {
                category: string | null;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string | null;
                uploadToken?: string;
            } | null;
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            } | null;
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string | null;
                    expiresAt?: string | null;
                };
                connections?: number;
                etaSeconds?: number | null;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            } | null;
            error: {
                code?: string | null;
                message: string | null;
            } | null;
            startedAt: string | null;
            finishedAt: string | null;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type PostApiDownloadTasksResponse = PostApiDownloadTasksResponses[keyof PostApiDownloadTasksResponses];

export type GetApiDownloadTasksEventsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        assignedTo?: 'me';
        category?: string;
        tag?: string;
        sortBy?: 'createdAt' | 'source' | 'category' | 'tags' | 'status' | 'progress' | 'eta';
        sortDir?: 'asc' | 'desc';
        page?: number;
        pageSize?: number;
    };
    url: '/api/download-tasks/events';
};

export type GetApiDownloadTasksEventsErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiDownloadTasksEventsError = GetApiDownloadTasksEventsErrors[keyof GetApiDownloadTasksEventsErrors];

export type GetApiDownloadTasksEventsResponses = {
    /**
     * Download task events
     */
    200: string;
};

export type GetApiDownloadTasksEventsResponse = GetApiDownloadTasksEventsResponses[keyof GetApiDownloadTasksEventsResponses];

export type GetApiDownloadTasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/download-tasks/{id}';
};

export type GetApiDownloadTasksByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type GetApiDownloadTasksByIdError = GetApiDownloadTasksByIdErrors[keyof GetApiDownloadTasksByIdErrors];

export type GetApiDownloadTasksByIdResponses = {
    /**
     * Download task
     */
    200: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string | null;
            };
            labels: {
                category: string | null;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string | null;
                uploadToken?: string;
            } | null;
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            } | null;
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string | null;
                    expiresAt?: string | null;
                };
                connections?: number;
                etaSeconds?: number | null;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            } | null;
            error: {
                code?: string | null;
                message: string | null;
            } | null;
            startedAt: string | null;
            finishedAt: string | null;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type GetApiDownloadTasksByIdResponse = GetApiDownloadTasksByIdResponses[keyof GetApiDownloadTasksByIdResponses];

export type PatchApiDownloadTasksByIdData = {
    body: {
        status?: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        progress?: {
            download?: {
                bytes: number;
                totalBytes?: number | null;
                bytesPerSecond: number;
            };
            upload?: {
                bytes: number;
                totalBytes?: number | null;
                bytesPerSecond: number;
            };
        };
        errorMessage?: string | null;
        resultObjectId?: string | null;
        runtime?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            state?: string;
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            message?: string;
            updatedAt?: string;
            progress?: {
                download: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
            };
            torrent?: {
                infoHash?: string;
                name?: string;
                seeders?: number;
                leechers?: number;
                peers?: number;
            };
            seeding?: {
                enabled?: boolean;
                active?: boolean;
                uploadedBytes?: number;
                uploadBytesPerSecond?: number;
                ratio?: number;
                startedAt?: string | null;
                expiresAt?: string | null;
            };
            connections?: number;
            etaSeconds?: number | null;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peers?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
                countryCode?: string;
                regionCode?: string;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        } | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/download-tasks/{id}';
};

export type PatchApiDownloadTasksByIdErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Insufficient credits
     */
    402: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Download task conflict
     */
    409: {
        error: string;
    };
};

export type PatchApiDownloadTasksByIdError = PatchApiDownloadTasksByIdErrors[keyof PatchApiDownloadTasksByIdErrors];

export type PatchApiDownloadTasksByIdResponses = {
    /**
     * Updated download task
     */
    200: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string | null;
            };
            labels: {
                category: string | null;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string | null;
                uploadToken?: string;
            } | null;
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            } | null;
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string | null;
                    expiresAt?: string | null;
                };
                connections?: number;
                etaSeconds?: number | null;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            } | null;
            error: {
                code?: string | null;
                message: string | null;
            } | null;
            startedAt: string | null;
            finishedAt: string | null;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type PatchApiDownloadTasksByIdResponse = PatchApiDownloadTasksByIdResponses[keyof PatchApiDownloadTasksByIdResponses];

export type PostApiDownloadTasksByIdActionsData = {
    body: {
        action: 'pause' | 'resume' | 'cancel' | 'retry' | 'restart' | 'delete';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/download-tasks/{id}/actions';
};

export type PostApiDownloadTasksByIdActionsErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Forbidden
     */
    403: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Invalid task state
     */
    409: {
        error: string;
    };
};

export type PostApiDownloadTasksByIdActionsError = PostApiDownloadTasksByIdActionsErrors[keyof PostApiDownloadTasksByIdActionsErrors];

export type PostApiDownloadTasksByIdActionsResponses = {
    /**
     * Task action result
     */
    200: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string | null;
            };
            labels: {
                category: string | null;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string | null;
                uploadToken?: string;
            } | null;
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number | null;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            } | null;
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number | null;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string | null;
                    expiresAt?: string | null;
                };
                connections?: number;
                etaSeconds?: number | null;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            } | null;
            error: {
                code?: string | null;
                message: string | null;
            } | null;
            startedAt: string | null;
            finishedAt: string | null;
            updatedAt: string;
        };
        createdAt: string;
    } | {
        id: string;
        deleted: true;
    };
};

export type PostApiDownloadTasksByIdActionsResponse = PostApiDownloadTasksByIdActionsResponses[keyof PostApiDownloadTasksByIdActionsResponses];

export type PostApiDownloaderHeartbeatData = {
    body: {
        version: string;
        hostname: string;
        platform: string;
        arch: string;
        engine: 'builtin' | 'aria2' | 'qbittorrent';
        capabilities: Array<string>;
        maxConcurrentTasks: number;
        currentTasks: number;
        downloadBps?: number;
        uploadBps?: number;
        freeDiskBytes?: number;
    };
    path?: never;
    query?: never;
    url: '/api/downloader/heartbeat';
};

export type PostApiDownloaderHeartbeatErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type PostApiDownloaderHeartbeatError = PostApiDownloaderHeartbeatErrors[keyof PostApiDownloaderHeartbeatErrors];

export type PostApiDownloaderHeartbeatResponses = {
    /**
     * Updated downloader
     */
    200: {
        id: string;
        name?: string;
        status?: 'online' | 'offline' | 'disabled';
        enabled?: boolean;
        heartbeat?: {
            version: string;
            hostname: string;
            platform: string;
            arch: string;
            engine: 'builtin' | 'aria2' | 'qbittorrent';
            capabilities: Array<string>;
            maxConcurrentTasks: number;
            currentTasks: number;
            downloadBps: number;
            uploadBps: number;
            freeDiskBytes: number;
        };
    };
};

export type PostApiDownloaderHeartbeatResponse = PostApiDownloaderHeartbeatResponses[keyof PostApiDownloaderHeartbeatResponses];

export type GetApiAdminDownloadersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/downloaders';
};

export type GetApiAdminDownloadersErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiAdminDownloadersError = GetApiAdminDownloadersErrors[keyof GetApiAdminDownloadersErrors];

export type GetApiAdminDownloadersResponses = {
    /**
     * Downloaders
     */
    200: {
        items: Array<{
            id: string;
            name?: string;
            status?: 'online' | 'offline' | 'disabled';
            enabled?: boolean;
            heartbeat?: {
                version: string;
                hostname: string;
                platform: string;
                arch: string;
                engine: 'builtin' | 'aria2' | 'qbittorrent';
                capabilities: Array<string>;
                maxConcurrentTasks: number;
                currentTasks: number;
                downloadBps: number;
                uploadBps: number;
                freeDiskBytes: number;
            };
        }>;
        total: number;
    };
};

export type GetApiAdminDownloadersResponse = GetApiAdminDownloadersResponses[keyof GetApiAdminDownloadersResponses];

export type PostApiAdminDownloadersData = {
    body: {
        name: string;
        heartbeat: {
            version: string;
            hostname: string;
            platform: string;
            arch: string;
            engine: 'builtin' | 'aria2' | 'qbittorrent';
            capabilities: Array<string>;
            maxConcurrentTasks: number;
            currentTasks: number;
            downloadBps?: number;
            uploadBps?: number;
            freeDiskBytes?: number;
        };
    };
    path?: never;
    query?: never;
    url: '/api/admin/downloaders';
};

export type PostApiAdminDownloadersErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type PostApiAdminDownloadersError = PostApiAdminDownloadersErrors[keyof PostApiAdminDownloadersErrors];

export type PostApiAdminDownloadersResponses = {
    /**
     * Downloader registration
     */
    201: {
        downloader: {
            id: string;
            name?: string;
            status?: 'online' | 'offline' | 'disabled';
            enabled?: boolean;
            heartbeat?: {
                version: string;
                hostname: string;
                platform: string;
                arch: string;
                engine: 'builtin' | 'aria2' | 'qbittorrent';
                capabilities: Array<string>;
                maxConcurrentTasks: number;
                currentTasks: number;
                downloadBps: number;
                uploadBps: number;
                freeDiskBytes: number;
            };
        };
        token: string;
    };
};

export type PostApiAdminDownloadersResponse = PostApiAdminDownloadersResponses[keyof PostApiAdminDownloadersResponses];

export type DeleteApiAdminDownloadersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/downloaders/{id}';
};

export type DeleteApiAdminDownloadersByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type DeleteApiAdminDownloadersByIdError = DeleteApiAdminDownloadersByIdErrors[keyof DeleteApiAdminDownloadersByIdErrors];

export type DeleteApiAdminDownloadersByIdResponses = {
    /**
     * Deleted downloader
     */
    200: {
        id: string;
        deleted: boolean;
    };
};

export type DeleteApiAdminDownloadersByIdResponse = DeleteApiAdminDownloadersByIdResponses[keyof DeleteApiAdminDownloadersByIdResponses];

export type PatchApiAdminDownloadersByIdData = {
    body: {
        name?: string;
        enabled?: boolean;
        remoteDownloadCreditBillingEnabled?: boolean;
        remoteDownloadCreditUnitBytes?: number;
        remoteDownloadCreditPerUnit?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/downloaders/{id}';
};

export type PatchApiAdminDownloadersByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type PatchApiAdminDownloadersByIdError = PatchApiAdminDownloadersByIdErrors[keyof PatchApiAdminDownloadersByIdErrors];

export type PatchApiAdminDownloadersByIdResponses = {
    /**
     * Updated downloader
     */
    200: {
        id: string;
        name?: string;
        status?: 'online' | 'offline' | 'disabled';
        enabled?: boolean;
        heartbeat?: {
            version: string;
            hostname: string;
            platform: string;
            arch: string;
            engine: 'builtin' | 'aria2' | 'qbittorrent';
            capabilities: Array<string>;
            maxConcurrentTasks: number;
            currentTasks: number;
            downloadBps: number;
            uploadBps: number;
            freeDiskBytes: number;
        };
    };
};

export type PatchApiAdminDownloadersByIdResponse = PatchApiAdminDownloadersByIdResponses[keyof PatchApiAdminDownloadersByIdResponses];

export type PostApiObjectsData = {
    body: {
        name: string;
        type: string;
        size?: number;
        parent?: string;
        dirtype?: number;
        onConflict?: 'fail' | 'rename' | 'replace';
    };
    path?: never;
    query?: never;
    url: '/api/objects';
};

export type PostApiObjectsErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Name conflict
     */
    409: ErrorResponse;
};

export type PostApiObjectsError = PostApiObjectsErrors[keyof PostApiObjectsErrors];

export type PostApiObjectsResponses = {
    /**
     * Object draft with upload URL
     */
    200: {
        id: string;
        name: string;
        uploadUrl?: string;
        contentDisposition?: string;
    };
    /**
     * Object draft with upload URL
     */
    201: {
        id: string;
        name: string;
        uploadUrl?: string;
        contentDisposition?: string;
    };
};

export type PostApiObjectsResponse = PostApiObjectsResponses[keyof PostApiObjectsResponses];

export type PatchApiObjectsByIdData = {
    body: {
        action: 'confirm';
        onConflict?: 'fail' | 'rename' | 'replace';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/objects/{id}';
};

export type PatchApiObjectsByIdErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type PatchApiObjectsByIdError = PatchApiObjectsByIdErrors[keyof PatchApiObjectsByIdErrors];

export type PatchApiObjectsByIdResponses = {
    /**
     * Confirmed object
     */
    200: {
        id: string;
        name: string;
        uploadUrl?: string;
        contentDisposition?: string;
    };
};

export type PatchApiObjectsByIdResponse = PatchApiObjectsByIdResponses[keyof PatchApiObjectsByIdResponses];

export type PostApiObjectsByIdUploadsData = {
    body: {
        partSize?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/objects/{id}/uploads';
};

export type PostApiObjectsByIdUploadsErrors = {
    /**
     * Invalid upload session
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type PostApiObjectsByIdUploadsError = PostApiObjectsByIdUploadsErrors[keyof PostApiObjectsByIdUploadsErrors];

export type PostApiObjectsByIdUploadsResponses = {
    /**
     * Object multipart upload session
     */
    201: {
        id: string;
        objectId: string;
        uploadId: string;
        partSize: number;
        status: 'active' | 'completed' | 'aborted';
        expiresAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiObjectsByIdUploadsResponse = PostApiObjectsByIdUploadsResponses[keyof PostApiObjectsByIdUploadsResponses];

export type PostApiObjectsByIdUploadsByUploadSessionIdPartsData = {
    body: {
        partNumbers: Array<number>;
    };
    path: {
        id: string;
        uploadSessionId: string;
    };
    query?: never;
    url: '/api/objects/{id}/uploads/{uploadSessionId}/parts';
};

export type PostApiObjectsByIdUploadsByUploadSessionIdPartsErrors = {
    /**
     * Invalid upload session
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type PostApiObjectsByIdUploadsByUploadSessionIdPartsError = PostApiObjectsByIdUploadsByUploadSessionIdPartsErrors[keyof PostApiObjectsByIdUploadsByUploadSessionIdPartsErrors];

export type PostApiObjectsByIdUploadsByUploadSessionIdPartsResponses = {
    /**
     * Presigned multipart upload parts
     */
    200: {
        uploadId: string;
        partSize: number;
        parts: Array<{
            partNumber: number;
            url: string;
        }>;
    };
};

export type PostApiObjectsByIdUploadsByUploadSessionIdPartsResponse = PostApiObjectsByIdUploadsByUploadSessionIdPartsResponses[keyof PostApiObjectsByIdUploadsByUploadSessionIdPartsResponses];

export type PatchApiObjectsByIdUploadsByUploadSessionIdData = {
    body: {
        action: 'complete';
        parts: Array<{
            partNumber: number;
            etag: string;
        }>;
    } | {
        action: 'abort';
    };
    path: {
        id: string;
        uploadSessionId: string;
    };
    query?: never;
    url: '/api/objects/{id}/uploads/{uploadSessionId}';
};

export type PatchApiObjectsByIdUploadsByUploadSessionIdErrors = {
    /**
     * Invalid upload session
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type PatchApiObjectsByIdUploadsByUploadSessionIdError = PatchApiObjectsByIdUploadsByUploadSessionIdErrors[keyof PatchApiObjectsByIdUploadsByUploadSessionIdErrors];

export type PatchApiObjectsByIdUploadsByUploadSessionIdResponses = {
    /**
     * Updated object multipart upload session
     */
    200: {
        id: string;
        objectId: string;
        uploadId: string;
        partSize: number;
        status: 'active' | 'completed' | 'aborted';
        expiresAt: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiObjectsByIdUploadsByUploadSessionIdResponse = PatchApiObjectsByIdUploadsByUploadSessionIdResponses[keyof PatchApiObjectsByIdUploadsByUploadSessionIdResponses];
