// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://raw.githubusercontent.com' | (string & {});
};

export type DeviceCode = {
    device_code: string;
    user_code: string;
    verification_uri: string;
    verification_uri_complete: string;
    expires_in: number;
    interval: number;
};

export type DeviceCodeRequest = {
    client_id: string;
    scope: string;
};

export type DeviceToken = {
    access_token: string;
    token_type: string;
    expires_in: number;
    scope: string;
};

export type ErrorResponse = {
    error: string;
};

export type DeviceTokenRequest = {
    grant_type: string;
    device_code: string;
    client_id: string;
};

export type ObjectDraft = {
    id: string;
    name: string;
    uploadUrl?: string;
    contentDisposition?: string;
};

export type ConfirmObjectRequest = {
    action: 'confirm';
};

export type PostApiAuthDeviceCodeData = {
    body: DeviceCodeRequest;
    path?: never;
    query?: never;
    url: '/api/auth/device/code';
};

export type PostApiAuthDeviceCodeResponses = {
    /**
     * Device authorization code
     */
    200: DeviceCode;
};

export type PostApiAuthDeviceCodeResponse = PostApiAuthDeviceCodeResponses[keyof PostApiAuthDeviceCodeResponses];

export type PostApiAuthDeviceTokenData = {
    body: DeviceTokenRequest;
    path?: never;
    query?: never;
    url: '/api/auth/device/token';
};

export type PostApiAuthDeviceTokenErrors = {
    /**
     * Device login error
     */
    400: ErrorResponse;
};

export type PostApiAuthDeviceTokenError = PostApiAuthDeviceTokenErrors[keyof PostApiAuthDeviceTokenErrors];

export type PostApiAuthDeviceTokenResponses = {
    /**
     * Device access token
     */
    200: DeviceToken;
};

export type PostApiAuthDeviceTokenResponse = PostApiAuthDeviceTokenResponses[keyof PostApiAuthDeviceTokenResponses];

export type GetApiDownloadTasksData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'pausing' | 'paused' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        assignedTo?: 'me';
        category?: string;
        tag?: string;
        sortBy?: 'createdAt' | 'source' | 'category' | 'tags' | 'status' | 'progress' | 'eta';
        sortDir?: 'asc' | 'desc';
        page?: number;
        pageSize?: number;
    };
    url: '/api/download-tasks';
};

export type GetApiDownloadTasksErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiDownloadTasksError = GetApiDownloadTasksErrors[keyof GetApiDownloadTasksErrors];

export type GetApiDownloadTasksResponses = {
    /**
     * Download tasks
     */
    200: {
        items: Array<{
            id: string;
            sourceType: 'http' | 'magnet' | 'torrent_url';
            sourceUri: string;
            name: string;
            targetFolder: string;
            category: string | null;
            tags: Array<string>;
            status: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'paused' | 'uploading' | 'completed' | 'failed' | 'canceled';
            downloadedBytes: number;
            storageUploadedBytes: number;
            totalBytes: number | null;
            downloadBps: number;
            storageUploadBps: number;
            errorMessage?: string | null;
            resultObjectId?: string | null;
            detail?: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                engineState?: string;
                message?: string;
                etaSeconds?: number | null;
                connections?: number;
                infoHash?: string;
                torrentName?: string;
                seeders?: number;
                leechers?: number;
                peers?: number;
                peerUploadedBytes?: number;
                peerUploadBps?: number;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peerSamples?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            } | null;
            uploadToken?: string;
            assignedDownloaderId?: string | null;
        }>;
        total: number;
        page: number;
        pageSize: number;
    };
};

export type GetApiDownloadTasksResponse = GetApiDownloadTasksResponses[keyof GetApiDownloadTasksResponses];

export type PostApiDownloadTasksData = {
    body: {
        source: {
            type: 'http' | 'magnet' | 'torrent_url';
            uri: string;
        };
        targetFolder: string;
        name?: string;
        category?: string;
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/download-tasks';
};

export type PostApiDownloadTasksErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Insufficient credits
     */
    402: {
        error: string;
    };
    /**
     * Download task conflict
     */
    409: {
        error: string;
    };
};

export type PostApiDownloadTasksError = PostApiDownloadTasksErrors[keyof PostApiDownloadTasksErrors];

export type PostApiDownloadTasksResponses = {
    /**
     * Created download task
     */
    201: {
        id: string;
        sourceType: 'http' | 'magnet' | 'torrent_url';
        sourceUri: string;
        name: string;
        targetFolder: string;
        category: string | null;
        tags: Array<string>;
        status: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'paused' | 'uploading' | 'completed' | 'failed' | 'canceled';
        downloadedBytes: number;
        storageUploadedBytes: number;
        totalBytes: number | null;
        downloadBps: number;
        storageUploadBps: number;
        errorMessage?: string | null;
        resultObjectId?: string | null;
        detail?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            engineState?: string;
            message?: string;
            etaSeconds?: number | null;
            connections?: number;
            infoHash?: string;
            torrentName?: string;
            seeders?: number;
            leechers?: number;
            peers?: number;
            peerUploadedBytes?: number;
            peerUploadBps?: number;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peerSamples?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        } | null;
        uploadToken?: string;
        assignedDownloaderId?: string | null;
    };
};

export type PostApiDownloadTasksResponse = PostApiDownloadTasksResponses[keyof PostApiDownloadTasksResponses];

export type GetApiDownloadTasksEventsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'pausing' | 'paused' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        assignedTo?: 'me';
        category?: string;
        tag?: string;
        sortBy?: 'createdAt' | 'source' | 'category' | 'tags' | 'status' | 'progress' | 'eta';
        sortDir?: 'asc' | 'desc';
        page?: number;
        pageSize?: number;
    };
    url: '/api/download-tasks/events';
};

export type GetApiDownloadTasksEventsErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiDownloadTasksEventsError = GetApiDownloadTasksEventsErrors[keyof GetApiDownloadTasksEventsErrors];

export type GetApiDownloadTasksEventsResponses = {
    /**
     * Download task events
     */
    200: string;
};

export type GetApiDownloadTasksEventsResponse = GetApiDownloadTasksEventsResponses[keyof GetApiDownloadTasksEventsResponses];

export type GetApiDownloadTasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/download-tasks/{id}';
};

export type GetApiDownloadTasksByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type GetApiDownloadTasksByIdError = GetApiDownloadTasksByIdErrors[keyof GetApiDownloadTasksByIdErrors];

export type GetApiDownloadTasksByIdResponses = {
    /**
     * Download task
     */
    200: {
        id: string;
        sourceType: 'http' | 'magnet' | 'torrent_url';
        sourceUri: string;
        name: string;
        targetFolder: string;
        category: string | null;
        tags: Array<string>;
        status: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'paused' | 'uploading' | 'completed' | 'failed' | 'canceled';
        downloadedBytes: number;
        storageUploadedBytes: number;
        totalBytes: number | null;
        downloadBps: number;
        storageUploadBps: number;
        errorMessage?: string | null;
        resultObjectId?: string | null;
        detail?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            engineState?: string;
            message?: string;
            etaSeconds?: number | null;
            connections?: number;
            infoHash?: string;
            torrentName?: string;
            seeders?: number;
            leechers?: number;
            peers?: number;
            peerUploadedBytes?: number;
            peerUploadBps?: number;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peerSamples?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        } | null;
        uploadToken?: string;
        assignedDownloaderId?: string | null;
    };
};

export type GetApiDownloadTasksByIdResponse = GetApiDownloadTasksByIdResponses[keyof GetApiDownloadTasksByIdResponses];

export type PatchApiDownloadTasksByIdData = {
    body: {
        status?: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'pausing' | 'paused' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        downloadedBytes?: number;
        storageUploadedBytes?: number;
        totalBytes?: number | null;
        downloadBps?: number;
        storageUploadBps?: number;
        errorMessage?: string | null;
        resultObjectId?: string | null;
        detail?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            engineState?: string;
            message?: string;
            etaSeconds?: number | null;
            connections?: number;
            infoHash?: string;
            torrentName?: string;
            seeders?: number;
            leechers?: number;
            peers?: number;
            peerUploadedBytes?: number;
            peerUploadBps?: number;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peerSamples?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        } | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/download-tasks/{id}';
};

export type PatchApiDownloadTasksByIdErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Insufficient credits
     */
    402: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Download task conflict
     */
    409: {
        error: string;
    };
};

export type PatchApiDownloadTasksByIdError = PatchApiDownloadTasksByIdErrors[keyof PatchApiDownloadTasksByIdErrors];

export type PatchApiDownloadTasksByIdResponses = {
    /**
     * Updated download task
     */
    200: {
        id: string;
        sourceType: 'http' | 'magnet' | 'torrent_url';
        sourceUri: string;
        name: string;
        targetFolder: string;
        category: string | null;
        tags: Array<string>;
        status: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'paused' | 'uploading' | 'completed' | 'failed' | 'canceled';
        downloadedBytes: number;
        storageUploadedBytes: number;
        totalBytes: number | null;
        downloadBps: number;
        storageUploadBps: number;
        errorMessage?: string | null;
        resultObjectId?: string | null;
        detail?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            engineState?: string;
            message?: string;
            etaSeconds?: number | null;
            connections?: number;
            infoHash?: string;
            torrentName?: string;
            seeders?: number;
            leechers?: number;
            peers?: number;
            peerUploadedBytes?: number;
            peerUploadBps?: number;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peerSamples?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        } | null;
        uploadToken?: string;
        assignedDownloaderId?: string | null;
    };
};

export type PatchApiDownloadTasksByIdResponse = PatchApiDownloadTasksByIdResponses[keyof PatchApiDownloadTasksByIdResponses];

export type PostApiDownloadTasksByIdActionsData = {
    body: {
        action: 'pause' | 'resume' | 'cancel' | 'retry' | 'delete';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/download-tasks/{id}/actions';
};

export type PostApiDownloadTasksByIdActionsErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Forbidden
     */
    403: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Invalid task state
     */
    409: {
        error: string;
    };
};

export type PostApiDownloadTasksByIdActionsError = PostApiDownloadTasksByIdActionsErrors[keyof PostApiDownloadTasksByIdActionsErrors];

export type PostApiDownloadTasksByIdActionsResponses = {
    /**
     * Task action result
     */
    200: {
        id: string;
        sourceType: 'http' | 'magnet' | 'torrent_url';
        sourceUri: string;
        name: string;
        targetFolder: string;
        category: string | null;
        tags: Array<string>;
        status: 'queued' | 'assigned' | 'running' | 'billing_paused' | 'paused' | 'uploading' | 'completed' | 'failed' | 'canceled';
        downloadedBytes: number;
        storageUploadedBytes: number;
        totalBytes: number | null;
        downloadBps: number;
        storageUploadBps: number;
        errorMessage?: string | null;
        resultObjectId?: string | null;
        detail?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            engineState?: string;
            message?: string;
            etaSeconds?: number | null;
            connections?: number;
            infoHash?: string;
            torrentName?: string;
            seeders?: number;
            leechers?: number;
            peers?: number;
            peerUploadedBytes?: number;
            peerUploadBps?: number;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peerSamples?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        } | null;
        uploadToken?: string;
        assignedDownloaderId?: string | null;
    } | {
        id: string;
        deleted: true;
    };
};

export type PostApiDownloadTasksByIdActionsResponse = PostApiDownloadTasksByIdActionsResponses[keyof PostApiDownloadTasksByIdActionsResponses];

export type PostApiDownloaderHeartbeatData = {
    body: {
        version: string;
        hostname: string;
        platform: string;
        arch: string;
        engine: 'builtin' | 'aria2' | 'qbittorrent';
        capabilities: Array<string>;
        maxConcurrentTasks: number;
        currentTasks: number;
        downloadBps?: number;
        uploadBps?: number;
        freeDiskBytes?: number;
    };
    path?: never;
    query?: never;
    url: '/api/downloader/heartbeat';
};

export type PostApiDownloaderHeartbeatErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type PostApiDownloaderHeartbeatError = PostApiDownloaderHeartbeatErrors[keyof PostApiDownloaderHeartbeatErrors];

export type PostApiDownloaderHeartbeatResponses = {
    /**
     * Updated downloader
     */
    200: {
        id: string;
        name?: string;
        status?: 'online' | 'offline' | 'disabled';
        enabled?: boolean;
        heartbeat?: {
            version: string;
            hostname: string;
            platform: string;
            arch: string;
            engine: 'builtin' | 'aria2' | 'qbittorrent';
            capabilities: Array<string>;
            maxConcurrentTasks: number;
            currentTasks: number;
            downloadBps: number;
            uploadBps: number;
            freeDiskBytes: number;
        };
    };
};

export type PostApiDownloaderHeartbeatResponse = PostApiDownloaderHeartbeatResponses[keyof PostApiDownloaderHeartbeatResponses];

export type GetApiAdminDownloadersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/downloaders';
};

export type GetApiAdminDownloadersErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiAdminDownloadersError = GetApiAdminDownloadersErrors[keyof GetApiAdminDownloadersErrors];

export type GetApiAdminDownloadersResponses = {
    /**
     * Downloaders
     */
    200: {
        items: Array<{
            id: string;
            name?: string;
            status?: 'online' | 'offline' | 'disabled';
            enabled?: boolean;
            heartbeat?: {
                version: string;
                hostname: string;
                platform: string;
                arch: string;
                engine: 'builtin' | 'aria2' | 'qbittorrent';
                capabilities: Array<string>;
                maxConcurrentTasks: number;
                currentTasks: number;
                downloadBps: number;
                uploadBps: number;
                freeDiskBytes: number;
            };
        }>;
        total: number;
    };
};

export type GetApiAdminDownloadersResponse = GetApiAdminDownloadersResponses[keyof GetApiAdminDownloadersResponses];

export type PostApiAdminDownloadersData = {
    body: {
        name: string;
        heartbeat: {
            version: string;
            hostname: string;
            platform: string;
            arch: string;
            engine: 'builtin' | 'aria2' | 'qbittorrent';
            capabilities: Array<string>;
            maxConcurrentTasks: number;
            currentTasks: number;
            downloadBps?: number;
            uploadBps?: number;
            freeDiskBytes?: number;
        };
    };
    path?: never;
    query?: never;
    url: '/api/admin/downloaders';
};

export type PostApiAdminDownloadersErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type PostApiAdminDownloadersError = PostApiAdminDownloadersErrors[keyof PostApiAdminDownloadersErrors];

export type PostApiAdminDownloadersResponses = {
    /**
     * Downloader registration
     */
    201: {
        downloader: {
            id: string;
            name?: string;
            status?: 'online' | 'offline' | 'disabled';
            enabled?: boolean;
            heartbeat?: {
                version: string;
                hostname: string;
                platform: string;
                arch: string;
                engine: 'builtin' | 'aria2' | 'qbittorrent';
                capabilities: Array<string>;
                maxConcurrentTasks: number;
                currentTasks: number;
                downloadBps: number;
                uploadBps: number;
                freeDiskBytes: number;
            };
        };
        token: string;
    };
};

export type PostApiAdminDownloadersResponse = PostApiAdminDownloadersResponses[keyof PostApiAdminDownloadersResponses];

export type DeleteApiAdminDownloadersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/downloaders/{id}';
};

export type DeleteApiAdminDownloadersByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type DeleteApiAdminDownloadersByIdError = DeleteApiAdminDownloadersByIdErrors[keyof DeleteApiAdminDownloadersByIdErrors];

export type DeleteApiAdminDownloadersByIdResponses = {
    /**
     * Deleted downloader
     */
    200: {
        id: string;
        deleted: boolean;
    };
};

export type DeleteApiAdminDownloadersByIdResponse = DeleteApiAdminDownloadersByIdResponses[keyof DeleteApiAdminDownloadersByIdResponses];

export type PatchApiAdminDownloadersByIdData = {
    body: {
        name?: string;
        enabled?: boolean;
        remoteDownloadCreditBillingEnabled?: boolean;
        remoteDownloadCreditUnitBytes?: number;
        remoteDownloadCreditPerUnit?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/downloaders/{id}';
};

export type PatchApiAdminDownloadersByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type PatchApiAdminDownloadersByIdError = PatchApiAdminDownloadersByIdErrors[keyof PatchApiAdminDownloadersByIdErrors];

export type PatchApiAdminDownloadersByIdResponses = {
    /**
     * Updated downloader
     */
    200: {
        id: string;
        name?: string;
        status?: 'online' | 'offline' | 'disabled';
        enabled?: boolean;
        heartbeat?: {
            version: string;
            hostname: string;
            platform: string;
            arch: string;
            engine: 'builtin' | 'aria2' | 'qbittorrent';
            capabilities: Array<string>;
            maxConcurrentTasks: number;
            currentTasks: number;
            downloadBps: number;
            uploadBps: number;
            freeDiskBytes: number;
        };
    };
};

export type PatchApiAdminDownloadersByIdResponse = PatchApiAdminDownloadersByIdResponses[keyof PatchApiAdminDownloadersByIdResponses];

export type PostApiObjectsData = {
    body: {
        name: string;
        type: string;
        size?: number;
        parent?: string;
        dirtype?: number;
        onConflict?: 'fail' | 'rename' | 'replace';
    };
    path?: never;
    query?: never;
    url: '/api/objects';
};

export type PostApiObjectsErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Name conflict
     */
    409: ErrorResponse;
};

export type PostApiObjectsError = PostApiObjectsErrors[keyof PostApiObjectsErrors];

export type PostApiObjectsResponses = {
    /**
     * Object draft with upload URL
     */
    200: ObjectDraft;
    /**
     * Object draft with upload URL
     */
    201: ObjectDraft;
};

export type PostApiObjectsResponse = PostApiObjectsResponses[keyof PostApiObjectsResponses];

export type PatchApiObjectsByIdData = {
    body: ConfirmObjectRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/objects/{id}';
};

export type PatchApiObjectsByIdErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
};

export type PatchApiObjectsByIdError = PatchApiObjectsByIdErrors[keyof PatchApiObjectsByIdErrors];

export type PatchApiObjectsByIdResponses = {
    /**
     * Confirmed object
     */
    200: ObjectDraft;
};

export type PatchApiObjectsByIdResponse = PatchApiObjectsByIdResponses[keyof PatchApiObjectsByIdResponses];
