// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiDownloadsTasksData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        assignedTo?: 'me';
        category?: string;
        tag?: string;
        sortBy?: 'createdAt' | 'source' | 'category' | 'tags' | 'status' | 'progress' | 'eta';
        sortDir?: 'asc' | 'desc';
        page?: number;
        pageSize?: number;
    };
    url: '/api/downloads/tasks';
};

export type GetApiDownloadsTasksErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiDownloadsTasksError = GetApiDownloadsTasksErrors[keyof GetApiDownloadsTasksErrors];

export type GetApiDownloadsTasksResponses = {
    /**
     * Download tasks
     */
    200: {
        items: Array<{
            id: string;
            orgId?: string;
            createdBy?: string;
            spec: {
                source: {
                    type: 'http' | 'magnet' | 'torrent_url';
                    uri: string;
                };
                destination: {
                    folder: string;
                    name: string;
                };
                labels: {
                    category: string;
                    tags: Array<string>;
                };
            };
            status: {
                state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
                attempt: number;
                assignment: {
                    downloaderId: string;
                    assignedAt?: string;
                    uploadToken?: string;
                };
                progress: {
                    download: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                };
                billing: {
                    state: 'none' | 'ok' | 'insufficient_credits';
                    authorizedBytes: number;
                    chargedBytes: number;
                    chargedCredits: number;
                };
                output: {
                    objectId: string;
                };
                runtime: {
                    engine?: 'builtin' | 'aria2' | 'qbittorrent';
                    state?: string;
                    phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                    message?: string;
                    updatedAt?: string;
                    progress?: {
                        download: {
                            bytes: number;
                            totalBytes?: number;
                            bytesPerSecond: number;
                        };
                        upload: {
                            bytes: number;
                            totalBytes?: number;
                            bytesPerSecond: number;
                        };
                    };
                    torrent?: {
                        infoHash?: string;
                        name?: string;
                        seeders?: number;
                        leechers?: number;
                        peers?: number;
                    };
                    seeding?: {
                        enabled?: boolean;
                        active?: boolean;
                        uploadedBytes?: number;
                        uploadBytesPerSecond?: number;
                        ratio?: number;
                        startedAt?: string;
                        expiresAt?: string;
                    };
                    connections?: number;
                    etaSeconds?: number;
                    trackers?: Array<{
                        url: string;
                        status?: string;
                        peers?: number;
                        seeds?: number;
                        leechers?: number;
                        message?: string;
                    }>;
                    peers?: Array<{
                        address: string;
                        client?: string;
                        progress?: number;
                        downloadBps?: number;
                        uploadBps?: number;
                        countryCode?: string;
                        regionCode?: string;
                    }>;
                    files?: Array<{
                        path: string;
                        size: number;
                        completedBytes?: number;
                        selected?: boolean;
                    }>;
                };
                error: {
                    code?: string;
                    message: string;
                };
                startedAt: string;
                finishedAt: string;
                updatedAt: string;
            };
            createdAt: string;
        }>;
        total: number;
        page: number;
        pageSize: number;
    };
};

export type GetApiDownloadsTasksResponse = GetApiDownloadsTasksResponses[keyof GetApiDownloadsTasksResponses];

export type PostApiDownloadsTasksData = {
    body: {
        source: {
            type: 'http' | 'magnet' | 'torrent_url';
            uri: string;
        };
        targetFolder: string;
        name?: string;
        category?: string;
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/downloads/tasks';
};

export type PostApiDownloadsTasksErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Insufficient credits
     */
    402: {
        error: string;
    };
    /**
     * Download task conflict
     */
    409: {
        error: string;
    };
};

export type PostApiDownloadsTasksError = PostApiDownloadsTasksErrors[keyof PostApiDownloadsTasksErrors];

export type PostApiDownloadsTasksResponses = {
    /**
     * Created download task
     */
    201: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string;
            };
            labels: {
                category: string;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string;
                uploadToken?: string;
            };
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            };
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string;
                    expiresAt?: string;
                };
                connections?: number;
                etaSeconds?: number;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            };
            error: {
                code?: string;
                message: string;
            };
            startedAt: string;
            finishedAt: string;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type PostApiDownloadsTasksResponse = PostApiDownloadsTasksResponses[keyof PostApiDownloadsTasksResponses];

export type DeleteApiDownloadsTasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/downloads/tasks/{id}';
};

export type DeleteApiDownloadsTasksByIdErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Forbidden
     */
    403: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Invalid task state
     */
    409: {
        error: string;
    };
};

export type DeleteApiDownloadsTasksByIdError = DeleteApiDownloadsTasksByIdErrors[keyof DeleteApiDownloadsTasksByIdErrors];

export type DeleteApiDownloadsTasksByIdResponses = {
    /**
     * Deleted download task
     */
    200: {
        id: string;
        deleted: true;
    };
};

export type DeleteApiDownloadsTasksByIdResponse = DeleteApiDownloadsTasksByIdResponses[keyof DeleteApiDownloadsTasksByIdResponses];

export type GetApiDownloadsTasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/downloads/tasks/{id}';
};

export type GetApiDownloadsTasksByIdErrors = {
    /**
     * Not found
     */
    404: {
        error: string;
    };
};

export type GetApiDownloadsTasksByIdError = GetApiDownloadsTasksByIdErrors[keyof GetApiDownloadsTasksByIdErrors];

export type GetApiDownloadsTasksByIdResponses = {
    /**
     * Download task
     */
    200: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string;
            };
            labels: {
                category: string;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string;
                uploadToken?: string;
            };
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            };
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string;
                    expiresAt?: string;
                };
                connections?: number;
                etaSeconds?: number;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            };
            error: {
                code?: string;
                message: string;
            };
            startedAt: string;
            finishedAt: string;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type GetApiDownloadsTasksByIdResponse = GetApiDownloadsTasksByIdResponses[keyof GetApiDownloadsTasksByIdResponses];

export type PatchApiDownloadsTasksByIdData = {
    body: {
        status?: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
        progress?: {
            download?: {
                bytes: number;
                totalBytes?: number;
                bytesPerSecond: number;
            };
            upload?: {
                bytes: number;
                totalBytes?: number;
                bytesPerSecond: number;
            };
        };
        errorMessage?: string;
        resultObjectId?: string;
        runtime?: {
            engine?: 'builtin' | 'aria2' | 'qbittorrent';
            state?: string;
            phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
            message?: string;
            updatedAt?: string;
            progress?: {
                download: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
            };
            torrent?: {
                infoHash?: string;
                name?: string;
                seeders?: number;
                leechers?: number;
                peers?: number;
            };
            seeding?: {
                enabled?: boolean;
                active?: boolean;
                uploadedBytes?: number;
                uploadBytesPerSecond?: number;
                ratio?: number;
                startedAt?: string;
                expiresAt?: string;
            };
            connections?: number;
            etaSeconds?: number;
            trackers?: Array<{
                url: string;
                status?: string;
                peers?: number;
                seeds?: number;
                leechers?: number;
                message?: string;
            }>;
            peers?: Array<{
                address: string;
                client?: string;
                progress?: number;
                downloadBps?: number;
                uploadBps?: number;
                countryCode?: string;
                regionCode?: string;
            }>;
            files?: Array<{
                path: string;
                size: number;
                completedBytes?: number;
                selected?: boolean;
            }>;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/downloads/tasks/{id}';
};

export type PatchApiDownloadsTasksByIdErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Insufficient credits
     */
    402: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Download task conflict
     */
    409: {
        error: string;
    };
};

export type PatchApiDownloadsTasksByIdError = PatchApiDownloadsTasksByIdErrors[keyof PatchApiDownloadsTasksByIdErrors];

export type PatchApiDownloadsTasksByIdResponses = {
    /**
     * Updated download task
     */
    200: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string;
            };
            labels: {
                category: string;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string;
                uploadToken?: string;
            };
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            };
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string;
                    expiresAt?: string;
                };
                connections?: number;
                etaSeconds?: number;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            };
            error: {
                code?: string;
                message: string;
            };
            startedAt: string;
            finishedAt: string;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type PatchApiDownloadsTasksByIdResponse = PatchApiDownloadsTasksByIdResponses[keyof PatchApiDownloadsTasksByIdResponses];

export type PutApiDownloadsTasksByIdStatusData = {
    body: {
        status: 'paused' | 'queued' | 'canceled';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/downloads/tasks/{id}/status';
};

export type PutApiDownloadsTasksByIdStatusErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Forbidden
     */
    403: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Invalid task state
     */
    409: {
        error: string;
    };
};

export type PutApiDownloadsTasksByIdStatusError = PutApiDownloadsTasksByIdStatusErrors[keyof PutApiDownloadsTasksByIdStatusErrors];

export type PutApiDownloadsTasksByIdStatusResponses = {
    /**
     * Updated download task
     */
    200: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string;
            };
            labels: {
                category: string;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string;
                uploadToken?: string;
            };
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            };
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string;
                    expiresAt?: string;
                };
                connections?: number;
                etaSeconds?: number;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            };
            error: {
                code?: string;
                message: string;
            };
            startedAt: string;
            finishedAt: string;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type PutApiDownloadsTasksByIdStatusResponse = PutApiDownloadsTasksByIdStatusResponses[keyof PutApiDownloadsTasksByIdStatusResponses];

export type PostApiDownloadsTasksByIdAttemptsData = {
    body: {
        fresh?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/downloads/tasks/{id}/attempts';
};

export type PostApiDownloadsTasksByIdAttemptsErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
    /**
     * Forbidden
     */
    403: {
        error: string;
    };
    /**
     * Not found
     */
    404: {
        error: string;
    };
    /**
     * Invalid task state
     */
    409: {
        error: string;
    };
};

export type PostApiDownloadsTasksByIdAttemptsError = PostApiDownloadsTasksByIdAttemptsErrors[keyof PostApiDownloadsTasksByIdAttemptsErrors];

export type PostApiDownloadsTasksByIdAttemptsResponses = {
    /**
     * New download attempt
     */
    201: {
        id: string;
        orgId?: string;
        createdBy?: string;
        spec: {
            source: {
                type: 'http' | 'magnet' | 'torrent_url';
                uri: string;
            };
            destination: {
                folder: string;
                name: string;
            };
            labels: {
                category: string;
                tags: Array<string>;
            };
        };
        status: {
            state: 'queued' | 'assigned' | 'downloading' | 'suspended' | 'pausing' | 'paused' | 'interrupted' | 'uploading' | 'canceling' | 'completed' | 'failed' | 'canceled';
            attempt: number;
            assignment: {
                downloaderId: string;
                assignedAt?: string;
                uploadToken?: string;
            };
            progress: {
                download: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
                upload: {
                    bytes: number;
                    totalBytes?: number;
                    bytesPerSecond: number;
                };
            };
            billing: {
                state: 'none' | 'ok' | 'insufficient_credits';
                authorizedBytes: number;
                chargedBytes: number;
                chargedCredits: number;
            };
            output: {
                objectId: string;
            };
            runtime: {
                engine?: 'builtin' | 'aria2' | 'qbittorrent';
                state?: string;
                phase?: 'metadata' | 'downloading' | 'uploading' | 'seeding' | 'completed' | 'error';
                message?: string;
                updatedAt?: string;
                progress?: {
                    download: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                    upload: {
                        bytes: number;
                        totalBytes?: number;
                        bytesPerSecond: number;
                    };
                };
                torrent?: {
                    infoHash?: string;
                    name?: string;
                    seeders?: number;
                    leechers?: number;
                    peers?: number;
                };
                seeding?: {
                    enabled?: boolean;
                    active?: boolean;
                    uploadedBytes?: number;
                    uploadBytesPerSecond?: number;
                    ratio?: number;
                    startedAt?: string;
                    expiresAt?: string;
                };
                connections?: number;
                etaSeconds?: number;
                trackers?: Array<{
                    url: string;
                    status?: string;
                    peers?: number;
                    seeds?: number;
                    leechers?: number;
                    message?: string;
                }>;
                peers?: Array<{
                    address: string;
                    client?: string;
                    progress?: number;
                    downloadBps?: number;
                    uploadBps?: number;
                    countryCode?: string;
                    regionCode?: string;
                }>;
                files?: Array<{
                    path: string;
                    size: number;
                    completedBytes?: number;
                    selected?: boolean;
                }>;
            };
            error: {
                code?: string;
                message: string;
            };
            startedAt: string;
            finishedAt: string;
            updatedAt: string;
        };
        createdAt: string;
    };
};

export type PostApiDownloadsTasksByIdAttemptsResponse = PostApiDownloadsTasksByIdAttemptsResponses[keyof PostApiDownloadsTasksByIdAttemptsResponses];

export type GetApiEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Set to "1" to subscribe to download-task events.
         */
        downloadTasks?: string;
        dtStatus?: string;
        dtCategory?: string;
        dtTag?: string;
        /**
         * One of: createdAt | source | category | tags | status | progress | eta
         */
        dtSortBy?: string;
        /**
         * asc | desc
         */
        dtSortDir?: string;
    };
    url: '/api/events';
};

export type GetApiEventsErrors = {
    /**
     * Unauthorized
     */
    401: {
        error: string;
    };
};

export type GetApiEventsError = GetApiEventsErrors[keyof GetApiEventsErrors];

export type GetApiEventsResponses = {
    /**
     * Open SSE stream of domain-change events
     */
    200: string;
};

export type GetApiEventsResponse = GetApiEventsResponses[keyof GetApiEventsResponses];
