import { describe, expect, it } from 'vitest'
import { analyzeIndexerRelease } from './release-analysis'
import type { IndexerSearchItem } from './types'

interface RealReleaseCase {
  title: string
  source: string
  resolution: string
  codec: string | null
  audio: string | null
  warnings: string[]
}

const realReleaseCases: RealReleaseCase[] = [
  {
    title: 'Битва за Землю / Captive State (2019) BDRemux 1080p | iTunes, HDRezka Studio, СВ Студия',
    source: 'REMUX',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Dune.2021.1080p.BluRay.REMUX.AVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT',
    source: 'REMUX',
    resolution: '1080p',
    codec: 'x264',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'Oppenheimer.2023.1080p.Bluray.REMUX.AVC.DTS-HD.MA.5.1-GHD[TGx]',
    source: 'REMUX',
    resolution: '1080p',
    codec: 'x264',
    audio: 'DTS-HD MA',
    warnings: [],
  },
  {
    title: 'Dune.2021.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT',
    source: 'REMUX',
    resolution: '2160p',
    codec: 'x265',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'Oppenheimer.2023.2160p.UHD.Bluray.REMUX.HDR10.HEVC.DTS-HD.MA.5.1',
    source: 'REMUX',
    resolution: '2160p',
    codec: 'x265',
    audio: 'DTS-HD MA',
    warnings: [],
  },
  {
    title: 'Dune 2021 REPACK 4K HDR DV 2160p BDRemux Ita Eng x265 NAHOM mkv',
    source: 'REMUX',
    resolution: '2160p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: 'Тайна третьей планеты (1981) BDRemux 1080p',
    source: 'REMUX',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'F1 The Movie (2025) BDRemux.1080p',
    source: 'REMUX',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'The Hateful Eight 2015 2160p REMUX DCPRip Eng DDR mkv',
    source: 'REMUX',
    resolution: '2160p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'The Hateful Eight 2015 4K UHD 2160p REMUX DCPRip DTS-HD 5.1-DDR',
    source: 'REMUX',
    resolution: '2160p',
    codec: null,
    audio: 'DTS',
    warnings: [],
  },
  {
    title: 'Оппенгеймер / Oppenheimer (2023) BDRip-IMAX',
    source: 'BluRay',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Oppenheimer.2023.1080p.BluRay.DD5.1.x264-GalaxyRG',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AC3',
    warnings: [],
  },
  {
    title: 'The.Sopranos.S01.1080p.BluRay.x265-',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: 'Twin.Peaks.S01.COMPLETE.1080p.10bit.BluRay.6CH.x265.HEVC-PSA',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: 'The.Sopranos.S02.1080p.BluRay.x265-',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: '28.Days.Later.2002.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'EAC3',
    warnings: [],
  },
  {
    title: 'Game.of.Thrones.S01.COMPLETE.1080p.10bit.BluRay.6CH.x265.HEVC-PS',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: 'House of the Dragon S01 1080p BluRay x265',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: 'The Boys (2019) S03 S03 (1080p BluRay x265 HEVC 10bit AAC 5.1 Silence)',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'AAC',
    warnings: [],
  },
  {
    title: 'The Boys (2019) S02 S02 (1080p BluRay x265 HEVC 10bit AAC 5',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'AAC',
    warnings: [],
  },
  {
    title: 'Mulholland.Drive.2001.Criterion.1080p.BluRay.x265.10bit.AAC 5.1',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'AAC',
    warnings: [],
  },
  {
    title: 'The.Martian.2015.EXTENDED.1080p.BluRay.DDP5.1.x265.10bit-GalaxyR',
    source: 'BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'EAC3',
    warnings: [],
  },
  {
    title: 'Masters of the Universe (2026) [1080p] [WEBRip]',
    source: 'WEBRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Project Hail Mary (2026) [1080p] [WEBRip] [5.1]',
    source: 'WEBRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Michael (2026) [1080p] [WEBRip] [5.1]',
    source: 'WEBRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'From.S04E10.1080p.WEBRip.10Bit.DDP5.1.x265-NeoNoir',
    source: 'WEBRip',
    resolution: '1080p',
    codec: 'x265',
    audio: 'EAC3',
    warnings: [],
  },
  {
    title: 'Mortal Kombat II (2026) [REPACK] [1080p] [WEBRip] [x265] [10bit] [5.1]',
    source: 'WEBRip',
    resolution: '1080p',
    codec: 'x265',
    audio: null,
    warnings: [],
  },
  {
    title: 'In the Grey (2026) [1080p] [WEBRip] [5.1]',
    source: 'WEBRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Avatar.The.Legend.of.Aang.The.Last.Airbender.2026.1080p.PMNTP.WEBRip.AAC2.0.H264-[LEAK].mp4',
    source: 'WEBRip',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: [],
  },
  {
    title: 'One Battle After Another (2025) [1080p] [WEBRip] [5.1]',
    source: 'WEBRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Retro (2025) 1080p Telugu DVDScr x264 AAC 2 9GB',
    source: 'Screener',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'Kaantha (2025) 720p Telugu DVDScr x264 AAC 950MB',
    source: 'Screener',
    resolution: '720p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'Protector 2025 1080p SCREENER WEB DL H264 AAC II',
    source: 'Screener',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'Fuze 2025 1080p READNFO SCREENER WEB DL H264 AAC AOC',
    source: 'Screener',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'Lokah Chapter 1 Chandra (2025) 720p Telugu DVDScr x264 AAC 1 4GB',
    source: 'Screener',
    resolution: '720p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'The Voice of Hind Rajab 2025 1080p SCREENER WEB DL H264 AAC AOC',
    source: 'Screener',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'Tere Ishk Mein (2025) v2 1080p Hindi DVDScr x264 AAC 2 7GB',
    source: 'Screener',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['screenerSource'],
  },
  {
    title: 'Portrait of A Lady on Fire.2019.DVDSCR.XviD.AC3-EVO[TGx]',
    source: 'Screener',
    resolution: 'other',
    codec: null,
    audio: 'AC3',
    warnings: ['screenerSource'],
  },
  {
    title: 'House of the Dragon S03E01 REPACK 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX',
    source: 'WEB-DL',
    resolution: '1080p',
    codec: 'x264',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'House.of.the.Dragon.S03E01.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX',
    source: 'WEB-DL',
    resolution: '1080p',
    codec: 'x264',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'House of the Dragon S03E01 REPACK 2160p HMAX WEB-DL DDP5 1 Atmos DV HDR H 265-FLUX',
    source: 'WEB-DL',
    resolution: '2160p',
    codec: 'x265',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'House of the Dragon S03E02 2160p HMAX WEB-DL DDP5 1 Atmos DV HDR H 265-FLUX',
    source: 'WEB-DL',
    resolution: '2160p',
    codec: 'x265',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'House of the Dragon S03E02 1080p AMZN WEB-DL DDP5 1 Atmos H 264-FLUX',
    source: 'WEB-DL',
    resolution: '1080p',
    codec: 'x264',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'House of the Dragon S03E02 1080p AMZN WEB DL DDP5 1 Atmos H 264 FLUX',
    source: 'WEB-DL',
    resolution: '1080p',
    codec: 'x264',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'Project.Hail.Mary.2026.2160p.WEB-DL.DDP5.1.Atmos.H.265-RDNYB',
    source: 'WEB-DL',
    resolution: '2160p',
    codec: 'x265',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'House of the Dragon S03E02 2160p HMAX WEB DL DDP5 1 Atmos DV HDR H 265 FLUX',
    source: 'WEB-DL',
    resolution: '2160p',
    codec: 'x265',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'The Boys S05E06 Though the Heavens Fall 1080p AMZN WEB-DL DDP5 1 Atmos H 264-playWEB',
    source: 'WEB-DL',
    resolution: '1080p',
    codec: 'x264',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'Блуждающая Земля / Liu lang di qiu (The Wandering Earth) (2019) WEB-DL',
    source: 'WEB-DL',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Deadpool amp Wolverine (2024) 1080p CAMRip English x264 1XBET',
    source: 'CAM',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Moana 2 (2024) 1080p V2 CAMRip English x264 1XBET',
    source: 'CAM',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Despicable Me 4 (2024) 1080p CAMRip [HIndi English] x264 1XBET',
    source: 'CAM',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Demon Slayer Infinity Castle 2025 Kimetsu no yaiba CAMRIP ENG SUB',
    source: 'CAM',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: '[BestGirl] Evangelion Broadcast 30th Anniversary Special Screening (CamRip)',
    source: 'CAM',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Rick And Morty S09E01 720p HDTV H 264-JFF',
    source: 'HDTV',
    resolution: '720p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'SpongeBob SquarePants S17E02 720p HDTV H264-JFF',
    source: 'HDTV',
    resolution: '720p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'Rick And Morty S09E01 720p HDTV H264-JFF',
    source: 'HDTV',
    resolution: '720p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'The.Rookie.S08E17.720p.HDTV.x264-SYNCOPY',
    source: 'HDTV',
    resolution: '720p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'The Rookie S08E12 720p HDTV x264-SYNCOPY',
    source: 'HDTV',
    resolution: '720p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'Obsession.2026.1080p.TELESYNC.x264-UNiON',
    source: 'Telesync',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Obsession 2026 1080p TELESYNC x264 UNiON',
    source: 'Telesync',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Supergirl.2026.1080p.TELESYNC.x264-DKS',
    source: 'Telesync',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Supergirl 2026 1080p TELESYNC x264 DKS',
    source: 'Telesync',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Toy.Story.5.2026.1080p.Telesync.h264.Dual.YG',
    source: 'Telesync',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Project.Hail.Mary.2026.1080p.TELESYNC.HC.x264-SyncUP',
    source: 'Telesync',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Star Wars: Episode V - The Empire Strikes Back.1980.BD50.MULTI',
    source: 'BDMV',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Eyes Wide Shut (1999) BD50 VC-1 LPCM-5.1 EUR-rutracker',
    source: 'BDMV',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Deadpool 2 2018 BluRay 720p x264 Dual Audio [Hindi Org BD50 DD 5 1 English] Hon3yHD',
    source: 'BDMV',
    resolution: '720p',
    codec: 'x264',
    audio: 'AC3',
    warnings: [],
  },
  {
    title: 'Robots 2005 BD50 MPEG-4 AVC DTS (20 Audios, 19 Subs) CHDBits',
    source: 'BDMV',
    resolution: 'other',
    codec: 'x264',
    audio: 'DTS',
    warnings: [],
  },
  {
    title: 'The Lion King 3D 1994 BD50 MPEG-4 AVC DTS - HD MA CEE [AreaFiles',
    source: 'BDMV',
    resolution: 'other',
    codec: 'x264',
    audio: 'DTS-HD MA',
    warnings: [],
  },
  {
    title: 'The Fantastic Four First Steps 2025 1080p HDCAM x264 SyncUP [CT]',
    source: 'HDCAM',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'The Fantastic Four First Steps [2025] 1080p HDCAM x264 DUAL AAC SUB',
    source: 'HDCAM',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['lowQualitySource'],
  },
  {
    title: 'The Naked Gun [2025] 1080p HDCAM x264 DUAL AC3 Buckfast',
    source: 'HDCAM',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AC3',
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Weapons [2025] 1080p HDCAM x265 HEVC 10Bit DUAL AC3 (UKBandit)',
    source: 'HDCAM',
    resolution: '1080p',
    codec: 'x265',
    audio: 'AC3',
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Captain America Brave New World 2025 1080p HDCAM C1NEM4',
    source: 'HDCAM',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Zootopia 2 [2025] 1080p HDCAM x264 AC3 (UKB)',
    source: 'HDCAM',
    resolution: '1080p',
    codec: 'x264',
    audio: 'AC3',
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Star Wars: Episode VII - The Force Awakens (2015)',
    source: 'Unknown source',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Chernobyl: Inside the Meltdown E1-4 of 4 (2026)',
    source: 'Unknown source',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Batman v Superman: Dawn of Justice (2016)',
    source: 'Unknown source',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Ice Age: Cosmic Scrat-tastrophe (2015) 2K DCP',
    source: 'Unknown source',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Мортал Комбат 2 / Mortal Kombat II (2026) DCPRip 1080p | Movie Dubbing',
    source: 'DCPRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'The Devil Wears Prada 2 2026 1080p DCPRip x264-FS',
    source: 'DCPRip',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'Star Wars The Mandalorian And Grogu 2026 1080p DCPRiP x264 FS',
    source: 'DCPRip',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'Дьявол носит Prada 2 / The Devil Wears Prada 2 (2026) DCPRip 1080p-MovieDalen',
    source: 'DCPRip',
    resolution: '1080p',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Star.Wars.The.Mandalorian.And.Grogu.2026.1080p.DCPRiP.x264-FS',
    source: 'DCPRip',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'Dune.2021.1080p.HDRip.X264-EVO[TGx]',
    source: 'HDRip',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'Dune.2021.HDRip.XviD-EVO[TGx]',
    source: 'HDRip',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Dune.2021.720p.HDRip.900MB.x264-GalaxyRG',
    source: 'HDRip',
    resolution: '720p',
    codec: 'x264',
    audio: null,
    warnings: [],
  },
  {
    title: 'The Thing 1982 REPACK UHD BluRay 1080p DDP 5 1 HDR10 x265 SM737',
    source: 'UHD BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'EAC3',
    warnings: [],
  },
  {
    title: 'Crime 101 2026 UHD BluRay 1080p DD Atmos 5 1 DoVi HDR10 x265 SM737',
    source: 'UHD BluRay',
    resolution: '1080p',
    codec: 'x265',
    audio: 'Atmos',
    warnings: [],
  },
  {
    title: 'Masters of the Universe.2026.1080p.TeleCine.h264.Latino.YG',
    source: 'Telecine',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Daybreakers 2009 TELECINE H264 AAC-SecretMyth (Kingdom-Release)',
    source: 'Telecine',
    resolution: 'other',
    codec: 'x264',
    audio: 'AAC',
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Bronson 2009 TELECINE [A Release-Lounge H264]',
    source: 'Telecine',
    resolution: 'other',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Smog 1962 ITA SUB ENG ITA Telecine XviD',
    source: 'Telecine',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Smurfs 2025 1080p TELECINE x264 Dual YG',
    source: 'Telecine',
    resolution: '1080p',
    codec: 'x264',
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Aladdin 2019 iTALiAN MD TELECINE XViD LFi[MT]',
    source: 'Telecine',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Avengers Endgame 2019 TeleCine',
    source: 'Telecine',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: ['lowQualitySource'],
  },
  {
    title: 'Movie 43 2013 R5 DVDRIP DIVX ENG-DUQA',
    source: 'R5',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'The.Skin.I.Live.In.2011.HC.ENG.SUBS.R5.DVDRiP.XviD-SiC',
    source: 'R5',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Pokemon The Movie Black Victini And Reshiram DVD5 (2011)',
    source: 'DVDRip',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
  {
    title: 'Sintel (2010)DVD5 nl subs NLT-Release',
    source: 'DVDRip',
    resolution: 'other',
    codec: null,
    audio: null,
    warnings: [],
  },
]

describe('real indexer release title analysis', () => {
  it('classifies 100 sampled real indexer release titles', () => {
    expect(realReleaseCases).toHaveLength(100)

    for (const item of realReleaseCases) {
      const analysis = analyzeIndexerRelease(release(item.title))
      expect(
        {
          source: analysis.source.label,
          resolution: analysis.resolution.id,
          codec: analysis.codec,
          audio: analysis.audio,
          warnings: analysis.warnings,
        },
        item.title,
      ).toEqual({
        source: item.source,
        resolution: item.resolution,
        codec: item.codec,
        audio: item.audio,
        warnings: item.warnings,
      })
    }
  })
})

function release(title: string): IndexerSearchItem {
  return {
    id: title,
    downloadTarget: null,
    title,
    fileName: null,
    indexer: 'Indexer',
    size: null,
    seeders: null,
    leechers: null,
    files: null,
    protocol: null,
    publishDate: null,
    downloadUrl: null,
    magnetUrl: null,
    infoUrl: null,
    infoHash: null,
    categories: [],
    categoryIds: [],
    indexerFlags: [],
    imdbId: null,
    tmdbId: null,
    tvdbId: null,
  }
}
